StormOnline/urls.py
# _ * _ coding: utf-8 _ * _
"""StormOnline URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Import the include() function: from django.conf.urls import url, include
    3. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
# ---------------python-------------------------
import xadmin
# ---------------django-------------------------
from django.conf.urls import url, include
from django.views.generic import TemplateView
from django.views.static import serve
from StormOnline.settings import MEDIA_ROOT
# ---------------model--------------------------
from users.views import LoginView, RegisterView, ActiveUserView, ForgetPwdView, ResetView, ModifyPwdView, LogoutView
from users.views import IndexView
from organization.views import OrgView

# ----------------url------------------------------
urlpatterns = [
    url(r'^xadmin/', xadmin.site.urls),
    url(r'^$', IndexView.as_view(), name="index"),

    # -------------------------user--------------------------
    url(r'^login/$', LoginView.as_view(), name="login"),
    url(r'^logout/$', LogoutView.as_view(), name="logout"),
    url(r'^register/$', RegisterView.as_view(), name="register"),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^active/(?P<active_code>.*)/$', ActiveUserView.as_view(), name="user_active"),
    url(r'^forget/$', ForgetPwdView.as_view(), name="forget_pwd"),
    url(r'^reset/(?P<reset_code>.*)/$', ResetView.as_view(), name="reset_pwd"),
    url(r'^modify/$', ModifyPwdView.as_view(), name="modify_pwd"),

    # -----------------------organization----------------------
    url(r'^org/', include('organization.urls', namespace="org", app_name='organization')),
    # -----------------------course-----------------------------
    url(r'^course/', include('courses.urls', namespace="course")),
    # -----------------------配置上传文件的访问处理函数路径---------------------
    url(r'^media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),
    #url(r'^static/(?P<path>.*)$', serve, {"document_root": STATIC_ROOT}),
    # -------------------------user_center---------------------------------
    url(r'^users/', include('users.urls', namespace="users")),
    # ----------------富文本编辑器-------------------------------------
    url(r'^ueditor/', include('DjangoUeditor.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls'))

]

# 全局404页面配置
handler404 = 'users.views.page_not_found'
# 全局500页面配置
handler500 = 'users.views.page_error'

apps/courses/urls.py
# _*_ coding: utf-8 _*_
# ---------------------------
__author__ = 'StormSha'
__date__ = '2018/3/20 11:18'
# ---------------------------

# ------------------django-----------------------------
from django.conf.urls import url, include
# -----------------model------------------------------
from .views import CourseListView, CourseDetailView, CourseInfoView, CommentsView, AddCommentsView, VideoPlayView, CommentsView1

urlpatterns = [
    url(r'^list/$', CourseListView.as_view(), name="course_list"),
    url(r'^detail/(?P<course_id>\d+)/$', CourseDetailView.as_view(), name="course_detail"),
    # 课程信息
    url(r'^info/(?P<course_id>\d+)/$', CourseInfoView.as_view(), name="course_info"),
    # 课程评论
    url(r'^comment/(?P<course_id>\d+)/$', CommentsView.as_view(), name="course_comment"),
    # 添加课程评论
    url(r'^add_comment/$', AddCommentsView.as_view(), name="add_comment"),
    # 视频播放
    url(r'^video/(?P<video_id>\d+)/$', VideoPlayView.as_view(), name="video_play"),
    # 会员课程评论
    url(r'^comment_1/(?P<course_id>\d+)/$', CommentsView1.as_view(), name="course_comment_1")
]

apps/organization/urls.py
# _*_ coding: utf-8 _*_
# ---------------------------
__author__ = 'StormSha'
__date__ = '2018/3/28 18:01'
# ---------------------------

# -------------------------django----------------------
from django.conf.urls import url
from .views import OrgView, AddUserAskView, OrgHomeView, OrgCourseView, OrgDescView, OrgTeacherView, AddFavView
from .views import TeacherListView, TeacherDetailView

urlpatterns = [
    url(r'^list/$', OrgView.as_view(), name="org_list"),
    url(r'^add_ask/$', AddUserAskView.as_view(), name="add_ask"),
    url(r'^home/(?P<org_id>\d+)/$', OrgHomeView.as_view(), name="org_home"),
    url(r'^course/(?P<org_id>\d+)/$', OrgCourseView.as_view(), name="org_course"),
    url(r'^desc/(?P<org_id>\d+)/$', OrgDescView.as_view(), name="org_desc"),
    url(r'^org_teacher/(?P<org_id>\d+)/$', OrgTeacherView.as_view(), name="org_teacher"),

    # --------------机构收藏-------------------------
    url(r'^add_fav/$', AddFavView.as_view(), name="add_fav"),
    # -----------------------teacher------------------------------
    url(r'^teacher/list/$', TeacherListView.as_view(), name="teacher_list"),
    url(r'^teacher/detail/(?P<teacher_id>\d+)/$', TeacherDetailView.as_view(), name="teacher_detail")
]

apps/users/urls.py
# encoding: utf-8
from django.conf.urls import url

from users.views import UserInfoView, UploadImageView, UpdatePwdView, UpdateEmailView, SendEmailCodeView
# , UpdatePwdView

from users.views import MyCourseView, MyFavOrgView, MyFavCourseView, MyFavTeacherView, MyMessageView

#

urlpatterns = [
    # -----用户信息-----------
    url(r'^info/', UserInfoView.as_view(), name="user_info"),
    # ----用户头像上传----------------------
    url(r'^image/upload/$', UploadImageView.as_view(), name="image_upload"),
    # ----用户中心修改密码-----------------
    url(r'^update/pwd/', UpdatePwdView.as_view(), name="update_pwd"),
    # 发送邮箱验证码
    url(r'^sendemail_code/$', SendEmailCodeView.as_view(), name="sendemail_code"),
    # 修改个人中心邮箱
    url(r'^update_email/$', UpdateEmailView.as_view(), name='update_email'),
    # -----我的课程-------------
    url(r'^my_course/', MyCourseView.as_view(), name="my_course"),
    # ----------我收藏的机构--------------
    url(r'^fav/org/', MyFavOrgView.as_view(), name="fav_org"),
    # ----------收藏的课程--------------------
    url(r'^fav/course/', MyFavCourseView.as_view(), name="fav_course"),
    # -----------收藏的讲师-----------------------
    url(r'^fav/teacher/', MyFavTeacherView.as_view(), name="fav_teacher"),
    # -----------我的消息-----------------------
    url(r'^my/message/', MyMessageView.as_view(), name="my_message")

]

ueditor/urls.py
#coding:utf-8
from django.conf.urls import include, url
from django.views.static import serve
from .controller import handler
import os

ueditor_path = os.path.join(os.path.dirname(__file__), "UE")

urlpatterns = [
    url(r'^$', handler),
    url(r'^UE/(?P<path>.*)$', serve, {'document_root': ueditor_path}),
]

apps/courses/models.py
# -*-coding:utf-8-*-
# -------------------python--------------
from __future__ import unicode_literals
from datetime import datetime
import sys
# -------------------django---------------
from django.db import models
# -------------------model----------------
from organization.models import CourseOrg, Teacher
from DjangoUeditor.models import UEditorField
# Create your models here.
reload(sys)
sys.setdefaultencoding('utf8')


class Course(models.Model):
    course_org = models.ForeignKey(CourseOrg, verbose_name=u"课程机构", null=True, blank=True)
    name = models.CharField(max_length=50, verbose_name=u"课程名")
    desc = models.CharField(max_length=300, verbose_name=u"课程描述")
    # 修改imagepath,不能传y m 进来，不能加斜杠是一个相对路径，相对于setting中配置的mediaroot
    detail = UEditorField(verbose_name=u"课程详情", width=600, height=300, imagePath="courses/ueditor/", filePath="courses/ueditor/", default='')
    is_banner = models.BooleanField(default=False, verbose_name=u"是否轮播")
    is_banner = models.BooleanField(default=False, verbose_name=u"是否轮播")
    teacher = models.ForeignKey(Teacher, verbose_name=u"讲师", null=True, blank=True)
    degree = models.CharField(verbose_name=u"难度", choices=(("cj", u"初级"), ("zj", u"中级"), ("gj", u"高级")), max_length=2)
    learn_times = models.IntegerField(default=0, verbose_name=u"学习时长(分钟)")
    students = models.IntegerField(default=0, verbose_name=u"学习人数")
    fav_nums = models.IntegerField(default=0, verbose_name=u"收藏人数")
    image = models.ImageField(upload_to="courses/%Y/%m", verbose_name=u"封面图", max_length=100)
    click_nums = models.IntegerField(default=0, verbose_name=u"点击数")
    category = models.CharField(default=u"python", max_length=50, verbose_name=u"课程类别")
    tag = models.CharField(default="", verbose_name=u"课程标签", max_length=20)
    you_know = models.CharField(default="", max_length=300, verbose_name=u"课程须知")
    teacher_tell = models.CharField(default="", max_length=300, verbose_name=u"老师说")
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u"添加时间")

    class Meta:
        verbose_name = u"课程"
        verbose_name_plural = verbose_name

    # -----获取课程章节数--------------
    def get_zj_nums(self):
        return self.lesson_set.all().count()

    def get_learn_users(self):
        return self.usercourse_set.all()[:5]

    # 获取课程所有章节
    def get_course_lesson(self):
        return self.lesson_set.all().order_by('-add_time')

    def __unicode__(self):
        return self.name


class Lesson(models.Model):
    course = models.ForeignKey(Course, verbose_name=u"课程")
    name = models.CharField(max_length=100, verbose_name=u"章节名")
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u"添加时间")

    class Meta:
        verbose_name = u"章节"
        verbose_name_plural = verbose_name

    # 获取章节视频
    def get_lesson_video(self):
        return self.video_set.all()

    def __unicode__(self):
        return self.name


class Video(models.Model):
    lesson = models.ForeignKey(Lesson, verbose_name=u"章节")
    name = models.CharField(max_length=100, verbose_name=u"视频名")
    url = models.CharField(max_length=200, default="", verbose_name=u"访问地址")
    learn_times = models.IntegerField(default=0, verbose_name=u"学习时长(分钟)")
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u"添加时间")

    class Meta:
        verbose_name = u"视频"
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.name


class CourseResource(models.Model):
    course = models.ForeignKey(Course, verbose_name=u"课程")
    name = models.CharField(max_length=100, verbose_name=u"名称")
    download = models.FileField(upload_to="course/resource/%Y/%m",verbose_name=u"资源文件", max_length=100)
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u"添加时间")

    class Meta:
        verbose_name = u"课程资源"
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.name

templates/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ message }}</title>
</head>
<body>

</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block title %} 课程机构列表 - 慕学在线网 {% endblock %}
{% load staticfiles %}
{% block custum_bread %}
{% endblock %}
{% block custom_js %}
    <script type="text/javascript" src="{% static 'js/index.js' %}"></script>
    <!-- 子导航 end -->
    <!-- 图片轮播 -->
    <script type="text/javascript">
      // 轮播数据
      window.SLIDEDATA = [
        // tab不提供则隐藏
        {'marginleft': 50, 'left': 65},
        {'marginleft': 32, 'left': 163}//,
        //{'marginleft': 34, 'left': 210}
      ];
    </script>
{% endblock %}
{% block content %}
    <div class="banner">
			<div class="wp">
				<div class="fl">
					<div class="imgslide">
						<ul class="imgs">
                            {% for banner in all_banner %}
                                <li>
                                        <a href="{{ banner.url }}">
                                            <img width="1200" height="478" src="{{ MEDIA_URL }}{{ banner.image }}" alt=""/>
                                        </a>
                                </li>
                            {% endfor %}
						</ul>
					</div>
					<div class="unslider-arrow prev"></div>
					<div class="unslider-arrow next"></div>
                    <div class="banner-vertical-nav">
                        <div class="tabtop"></div>
                        <div class="tabs f-pa">
                            <ul class="tabs-url clear f-f0">
                                <li class="j-tab tab f-f1 tabpos" style="margin-left: 50px">热门课程</li>
                            </ul>
                            <div class="tabline f-pa j-tabline" style="left: 65px;"></div>
                        </div>
                        <div class="tabcon">
                            <div class="tabbox f-pa j-mainslide-tabcon" style="display: block;">
                                <div class="listwrap">
                                    <ul class="list long j-hotlist">
                                        <li>
                                            <a href="http://127.0.0.1:8000/course/detail/6/" target="_blank" class="item">
                                                <i class="icon icon2">01</i>
                                                <span class="ltxt f-ib f-thide">软件开发:  零基础学习</span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="http://127.0.0.1:8000/course/detail/5/" target="_blank" class="item">
                                                <i class="icon icon2">02</i>
                                                <span class="ltxt f-ib f-thide">软件开发: 斯皮尔伯格演讲</span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="http://127.0.0.1:8000/course/detail/2/" target="_blank" class="item">
                                                <i class="icon icon2">03</i>
                                                <span class="ltxt f-ib f-thide">软件开发: web开发</span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="http://127.0.0.1:8000/course/detail/10/" target="_blank" class="item">
                                                <i class="icon">04</i>
                                                <span class="ltxt f-ib f-thide">软件开发: java课程</span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="http://127.0.0.1:8000/course/detail/6/" target="_blank" class="item">
                                                <i class="icon">05</i>
                                                <span class="ltxt f-ib f-thide">软件开发: Python入门</span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="http://127.0.0.1:8000/course/detail/6/" target="_blank" class="item">
                                                <i class="icon">06</i>
                                                <span class="ltxt f-ib f-thide">软件开发: Python大数据</span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="http://127.0.0.1:8000/course/detail/6/" target="_blank" class="item">
                                                <i class="icon">07</i>
                                                <span class="ltxt f-ib f-thide">软件开发: Python桌面开发</span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="http://127.0.0.1:8000/course/detail/6/" target="_blank" class="item">
                                                <i class="icon">08</i>
                                                <span class="ltxt f-ib f-thide">软件开发: Python人工智能</span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="http://127.0.0.1:8000/course/detail/6/" target="_blank" class="item">
                                                <i class="icon">09</i>
                                                <span class="ltxt f-ib f-thide">软件开发: Android开发</span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="http://127.0.0.1:8000/course/detail/6/" target="_blank" class="item">
                                                <i class="icon">10</i>
                                                <span class="ltxt f-ib f-thide">软件开发: Python全栈开发</span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="http://127.0.0.1:8000/course/detail/6/" target="_blank" class="item">
                                                <i class="icon">11</i>
                                                <span class="ltxt f-ib f-thide">软件开发: 网络营销</span>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
				</div>
            </div>
    </div>
<!--banner end-->
<!--feature start-->
	<section>
		<div class="wp">
			<ul class="feature">
				<li class="feature1">
					<img class="pic" src="{% static 'images/feature1.png' %}"/>
					<p class="center">专业权威</p>
				</li>
				<li class="feature2">
					<img class="pic" src="{% static 'images/feature2.png' %}"/>
					<p class="center">课程最新</p>
				</li>
				<li class="feature3">
					<img class="pic" src="{% static 'images/feature3.png' %}"/>
					<p class="center">名师授课</p>
				</li>
				<li class="feature4">
					<img class="pic" src="{% static 'images/feature4.png' %}"/>
					<p class="center">数据真实</p>
				</li>
			</ul>
		</div>
	</section>
<!--feature end-->
<!--module1 start-->
	<section>
		<div class="module">
			<div class="wp">
				<h1>公开课程</h1>
				<div class="module1 eachmod">
					<div class="module1_1 left">
						<img width="228" height="614" src="{% static 'images/module1_1.jpg' %}"/>
						<p class="fisrt_word">名师授课<br/>专业权威</p>
						<a class="more" href="{% url 'course:course_list' %}">查看更多课程 ></a>
					</div>
					<div class="right group_list">
						<div class="module1_2 box">
							<div class="imgslide2">
								<ul class="imgs">

                                    {% for banner_course in banner_courses %}
                                        <li>
                                        <a href="{% url 'course:course_detail' banner_course.id %}">
                                            <img width="470" height="300" src="{{ MEDIA_URL }}{{ banner_course.image }}" />
                                        </a>
                                    </li>
                                    {% endfor %}
								</ul>
							</div>
							<div class="unslider-arrow2 prev"></div>
							<div class="unslider-arrow2 next"></div>
						</div>
                        {% for course in courses %}
                            <div class="module1_{{ forloop.counter|add:2 }} box">
                                <a href="{% url 'course:course_detail' course.id  %}">
                                    <img width="233" height="190" src="{{ MEDIA_URL }}{{ course.image }}"/>
                                </a>
                                <div class="des">
                                    <a href="{% url 'course:course_detail' course.id  %}">
                                        <h2 title="{{ course.name }}">{{ course.name }}</h2>
                                    </a>
                                    <span class="fl">难度：<i class="key">{{ course.get_degree_display }}</i></span>
                                    <span class="fr">学习人数：{{ course.students }}</span>
                                </div>
                                <div class="bottom">
                                    <span class="fl" title="{{ course.course_org.name }}">{{ course.course_org.name }}</span>
                                    <span class="star fr">{{ course.fav_nums }}</span>
                                </div>
                            </div>
                        {% endfor %}

					</div>
				</div>
			</div>
		</div>
	</section>
	<section>
		<div class="module greybg">
			<div class="wp">
				<h1>课程机构</h1>
				<div class="module3 eachmod">
					<div class="module3_1 left">
						<img width="228" height="463" src="{% static 'images/module3_1.jpg' %}"/>
						<p class="fisrt_word">名校来袭<br/>权威认证</p>
						<a class="more" href="{% url 'org:org_list' %}">查看更多机构 ></a>
					</div>
					<div class="right">
						<ul>
                            {% for org in course_orgs %}
                                <li class="{% if forloop.counter|divisibleby:'5' %}five{% endif %}">
                                    <a href="{% url 'org:org_home' org.id %}">
                                        <div class="company">
                                            <img width="184" height="100" src="{{ MEDIA_URL }}{{ org.image }}"/>
                                            <div class="score">
                                                <div class="circle" style="display: none">
                                                    <h2>{{ org.tag }}</h2>
                                                </div>
                                            </div>
                                        </div>
                                        <p><span class="key" title="{{ org.name }}">{{ org.name }}</span></p>
                                    </a>
                                </li>
                            {% endfor %}
						</ul>
					</div>
				</div>
			</div>
		</div>
	</section>
{% endblock %}

templates/org_base.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
	<title>{% block title %}机构首页{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'js/plugins/queryCity/css/cityLayout.css' %}">
    {% block custom_css %}{% endblock %}
    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}" type="text/javascript"></script>
    {% block custom_js %}{% endblock %}
</head>
<body>
<section class="headerwrap headerwrap2">
    <header>
		<div  class="header2 header">
                {% if request.user.is_authenticated %}
                <div class="top">
				<div class="wp">
					<div class="fl">
                        <p>服务电话：<b>13298393221</b></p>
                    </div>
                    <!--登录后跳转-->
                    <div class="personal">
                        <dl class="user fr">
                            <dd>stormsha<img class="down fr" src="{% static 'images/top_down.png' %}"/></dd>
                            <dt><img width="20" height="20" src="{% static 'media/image/2016/12/default_big_14.png' %}"/></dt>
                        </dl>
                        <div class="userdetail">
                            <dl>
                                <dt><img width="80" height="80" src="{% static 'media/image/2016/12/default_big_14.png' %}"/></dt>
                                <dd>
                                    <h2>django</h2>
                                    <p>stormsha</p>
                                </dd>
                            </dl>
                            <div class="btn">
                                <a class="personcenter fl" href="usercenter-info.html">进入个人中心</a>
                                <a class="fr" href="/logout/">退出</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
                {% else %}
                <div class="top">
				<div class="wp">
					<div class="fl">
                        <p>服务电话：<b>13298393221</b></p>
                    </div>
                    <a style="color:white" class="fr registerbtn" href={% url 'register' %}>注册</a>
                    <a style="color:white" class="fr loginbtn" href="{% url 'login' %}">登录</a>
                </div>
            </div>
            {% endif %}
            <div class="middle companyheader">
                <div class="wp">
                    <img class="fl" style="width: 112px;height: 103px" src="{{ MEDIA_URL }}{{ course_org.image }}"/>
                    <div class="head fl">
                        <h1>
                            {{ course_org.name }}
                            <img src="{% static 'images/authentication.png' %}"/>
                            <img src="{% static 'images/gold.png' %}"/>
                        </h1>
                        <p class="fl">
                            <span class="fl" style="margin-top:8px;color:#848484;">推荐指数： </span>
                            <span class="precision company-credit" data-star-scope="5.0"></span>
                            <span class="key">5.0</span>
                        </p>
                    </div>
                    <div class="btn fr collectionbtn notlogin
                        "data-favid="22" data-fav-type="1" style="background: #ff8833 url({% static 'images/star-btn.png' %}) no-repeat 15px center;" >
                             {% if  has_fav %}
                                 已收藏
                             {% else %}
                                 收藏
                             {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </header>
</section>
<section>
	<div class="wp">
		<ul  class="crumbs">
            <li><a href="{% url 'index' %}">首页</a>></li>
			<li><a href="{% url 'org:org_list' %}">课程机构</a>></li>
			<li>{% block page_path %}机构首页{% endblock %}</li>
		</ul>
	</div>
</section>

<section>
	<div class="wp list personal_list comp">
		<div class="left">
			<ul>
				<li class="{% ifequal current_page 'home' %}active2{% endifequal %}"><a href="{% url 'org:org_home' course_org.id %}">机构首页</a></li>
                <li class="{% ifequal current_page 'course' %}active2{% endifequal %}"><a href="{% url 'org:org_course' course_org.id %}">机构课程</a></li>
                <li class="{% ifequal current_page 'desc' %}active2{% endifequal %}"><a href="{% url 'org:org_desc' course_org.id %}">机构介绍</a></li>
                <li class="{% ifequal current_page 'teacher' %}active2{% endifequal %}"><a href="{% url 'org:org_teacher' course_org.id %}">机构讲师</a></li>
			</ul>
        </div>
        {% block right_form %}
        {% endblock %}
    </div>
</section>
<!--sidebar start-->
<section>
    <ul class="sidebar">
        <li class="qq">
            <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2023525077&site=qq&menu=yes"></a>
        </li>
        <li class="totop"></li>
    </ul>
</section>
<!--sidebar end-->
<!--header start-->
</div>
<!--弹出省省市-->
<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script type="text/javascript" src="{% static 'js/plugins/laydate/laydate.js' %}"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js' %}" type="text/javascript"></script>

<script type="text/javascript" src="{% static 'js/plugins/jquery.raty.js' %}"></script>
<script type="text/javascript">
    //收藏分享
//收藏分享
function add_fav(current_elem, fav_id, fav_type){
    $.ajax({
        cache: false,
        type: "POST",
        url:"{% url 'org:add_fav' %}",
        data:{'fav_id':fav_id, 'fav_type':fav_type},
        async: true,
        beforeSend:function(xhr, settings){
            xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
        },
        success: function(data) {
            if(data.status == 'fail'){
                if(data.msg == '用户未登录'){
                    window.location.href="/login/";
                }else{
                    alert(data.msg)
                }

            }else if(data.status == 'success'){
                current_elem.text(data.msg)
            }
        },
    });
}

$('.collectionbtn').on('click', function(){
    add_fav($(this), {{ course_org.id }}, 2);
});

$(function(){
    var $precision = $('.precision'),
        score = $precision.attr('data-star-scope'),
        option =  {
                    half		: true,
                    path		: '{% static 'images/' %}',
                    precision	: true,
                    size		: 24,
                    starOff		: 'g_star.png',
                    starOn		: 'r_star.png',
                    starHalf	: 'h_star.png',
                    hints       : ['极差', '差', '一般', '好评', '非常满意'],
                    noRatedMsg  : '暂时还未获得评价！',
                    readOnly    : true,
                    score       : score
                };
    $precision.raty(option);

    $('.jsFavBtn').on('click', function(){
        var type = $(this).attr('data-fav-type');
        if(type == '1'){
            favPraise($(this), 'fav' ,1 , '收藏');

        }else if(type == '3'){
            favPraise($(this), 'fav' ,3 );

        }else if(type == '11'){
            favPraise($(this), 'pra', 1);

        }else if(type == '4'){
            favPraise($(this), 'fav' ,4 );

        }
    });
})
</script>


<script type="text/javascript">
$(function() {
    $('.recordbtn1').click(function(){
        $('.recordbox1').show();
    });
    $('.recordbtn2').click(function(){
        $('.recordbox2').show();
    });

    $('.imgslide').unslider({
        speed: 500,               //  The speed to animate each slide (in milliseconds)
        delay: 3000,              //  The delay between slide animations (in milliseconds)
        complete: function() {},  //  A function that gets called after every slide animation
        keys: true,               //  Enable keyboard (left, right) arrow shortcuts
        dots: true,               //  Display dot navigation
        fluid: false              //  Support responsive design. May break non-responsive designs
    });
    var unslider = $('.imgslide').unslider();
    $('.unslider-arrow').click(function() {
        var fn = this.className.split(' ')[1];
        unslider.data('unslider')[fn]();
    });
});
</script>

</body>
</html>